# Generated by Django 5.1.5 on 2025-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=200)),
                ('business_size', models.CharField(max_length=100)),
                ('digitalization_level', models.CharField(choices=[('basic', 'Basic - Minimal digital tools'), ('intermediate', 'Intermediate - Some digital processes'), ('advanced', 'Advanced - Highly digitalized')], max_length=50)),
                ('company_summary', models.TextField(blank=True)),
                ('ai_readiness_score', models.IntegerField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommended_use_cases', models.JSONField(blank=True, default=list)),
                ('quick_wins', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
