# Generated by Django 5.1.5 on 2025-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyassessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'KI-Bewertung', 'verbose_name_plural': 'KI-Bewertungen'},
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyassessment',
            name='questionnaire_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
