# Generated by Django 5.1.5 on 2025-11-15 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_companyassessment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=100)),
                ('revenue', models.CharField(max_length=100)),
                ('main_goal', models.JSONField(default=list)),
                ('urgency', models.IntegerField()),
                ('budget', models.CharField(max_length=100)),
                ('priority_processes', models.JSONField(default=list)),
                ('pain_points', models.JSONField(default=list)),
                ('detailed_challenges', models.TextField(blank=True)),
                ('crm_system', models.CharField(blank=True, max_length=255)),
                ('marketing_tools', models.JSONField(default=list)),
                ('service_tools', models.JSONField(default=list)),
                ('data_sources', models.JSONField(default=list)),
                ('api_access', models.CharField(blank=True, max_length=100)),
                ('monthly_leads', models.IntegerField(blank=True, null=True)),
                ('monthly_tickets', models.IntegerField(blank=True, null=True)),
                ('recurring_tasks', models.JSONField(default=list)),
                ('desired_outputs', models.JSONField(default=list)),
                ('data_privacy_importance', models.IntegerField()),
                ('languages', models.JSONField(default=list)),
                ('success_metrics', models.JSONField(default=list)),
                ('team_acceptance', models.IntegerField()),
                ('responsible_person', models.CharField(max_length=255)),
                ('consent_given', models.BooleanField(default=False)),
                ('calculated_score', models.IntegerField(blank=True, null=True)),
                ('score_level', models.CharField(blank=True, max_length=50)),
                ('analysis_completed', models.BooleanField(default=False)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('raw_answers', models.JSONField(blank=True, default=dict)),
                ('chatgpt_analysis', models.JSONField(blank=True, default=dict)),
                ('report_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'KI-Bewertung',
                'verbose_name_plural': 'KI-Bewertungen',
                'db_table': 'ai_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CompanyAssessment',
        ),
    ]
